# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 017b4daf7ea6118d5aeefc10ec74b067063fbc75d80b71921c1b8a6a0975061faf294251d2d1775921fa2185f5f0c22e4da26e7ccaf99c612f6e3f30d6582369

test:
  secret_key_base: 4bb7b9cfbda814140fe5ea6f0bbfd45c289799063fd5b70e24c78c7e3bad7c49982c6a4644f554e5eaead564c9738ebbb0ce42a60dab9ab4ac0fdd9d0696732b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
